In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from statistics import mean
from statistics import stdev
from statistics import variance
import random

In [2]:
df = pd.read_excel('Data Team Version IDIS Team Formation.xlsx')

In [3]:
df

,Respondent #,Gender,Teammate 1 (Repsondent #),Teammate 2 (Repsondent #),Liberal Arts,Health Sciences,Science,Technology,Engineering,Mathematics,...,Business/Commerce - General,"Eastern Standard Time - EST (London, Ontario)",1 to 3 hours behind EST,4 to 6 hours behind EST,Greater than 6 hours behind EST,1 to 3 hours ahead EST,4 to 6 hours ahead EST,Greater than 6 hours ahead EST,Remote Community Health Services,Sustainable Use of Fishery Resources
0,2,2,46,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
1,27,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Mathematics,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Greater than 6 hours ahead EST,Remote Community Health Services,NaN
2,5,1,11&39,6,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
3,32,1,11&39,NaN,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
4,29,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Business/Commerce - General,NaN,NaN,NaN,NaN,1 to 3 hours ahead EST,NaN,NaN,Remote Community Health Services,NaN
5,41,1,46,37,NaN,Health Sciences,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
6,24,2,42,21,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
7,4,1,5&32,6,NaN,NaN,NaN,NaN,NaN,NaN,...,Business/Commerce - General,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
8,31,1,5&32,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Business/Commerce - General,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
9,28,2,44,43,NaN,NaN,NaN,NaN,Engineering,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
10,26,1,25,NR8,NaN,Health Sciences,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
11,43,2,36,16,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
12,47,2,29,7,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
13,6,2,11&39,5&32,NaN,NaN,NaN,NaN,NaN,NaN,...,Business/Commerce - General,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
14,17,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
15,34,1,33,5&32,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sustainable Use of Fishery Resources
16,11,1,14,40,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sustainable Use of Fishery Resources
17,39,1,40,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sustainable Use of Fishery Resources
18,23,2,22,37,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
19,33,2,34,5&32,NaN,NaN,NaN,NaN,NaN,NaN,...,Business/Commerce - General,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sustainable Use of Fishery Resources
20,3,1,30,NaN,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
21,13,2,NaN,NaN,Liberal Arts,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sustainable Use of Fishery Resources
22,35,1,NaN,NaN,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
23,21,1,42,24,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
24,16,1,18,44,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
25,38,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
26,44,2,43,36,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
27,10,2,37,13,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4 to 6 hours ahead EST,NaN,Remote Community Health Services,NaN
28,20,1,19,NaN,Liberal Arts,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
29,40,1,11&39,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sustainable Use of Fishery Resources
30,12,1,22,NaN,NaN,NaN,NaN,NaN,Engineering,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Greater than 6 hours ahead EST,Remote Community Health Services,NaN
31,14,1,11&39,40,NaN,NaN,NaN,NaN,NaN,NaN,...,Business/Commerce - General,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,NaN,Sustainable Use of Fishery Resources
32,7,1,29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
33,9,1,NR1,19,NaN,NaN,NaN,NaN,Engineering,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
34,19,1,20,9,NaN,NaN,NaN,NaN,Engineering,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
35,37,1,41,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
36,22,1,12,NaN,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
37,45,2,NaN,NaN,NaN,NaN,Science,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
38,36,2,16,18,NaN,NaN,NaN,Technology,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
39,15,1,34,43,NaN,Health Sciences,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
40,8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
41,25,1,26,NaN,NaN,NaN,NaN,NaN,Engineering,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
42,46,1,37,41,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
43,18,2,28,16,Liberal Arts,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
44,42,1,21,24,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
45,30,1,NaN,NaN,Liberal Arts,NaN,NaN,NaN,NaN,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
46,1,2,2,NaN,NaN,NaN,NaN,NaN,Engineering,NaN,...,NaN,"Eastern Standard Time - EST (London, Ontario)",NaN,NaN,NaN,NaN,NaN,NaN,Remote Community Health Services,NaN
47,NR1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
48,NR2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
49,NR3,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,NR4,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
51,NR5,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
52,NR6,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
53,NR7,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
54,NR8,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df['Specialization'] = df[df.columns[4:13]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)
df['Client Preference'] = df[df.columns[20:22]].apply(
    lambda x: ','.join(x.dropna().astype(str)),
    axis=1
)
df_short = df.drop(['Liberal Arts', 'Health Sciences', 'Science', 'Technology', 'Engineering','Mathematics',
         'Business/Commerce - Marketing and Advertising', 'Business/Commerce - Finance and Accounting',
         'Business/Commerce - General', 'Eastern Standard Time - EST (London, Ontario)', '1 to 3 hours behind EST',
         '4 to 6 hours behind EST', 'Greater than 6 hours behind EST', '1 to 3 hours ahead EST',
         '1 to 3 hours ahead EST', '4 to 6 hours ahead EST', 'Greater than 6 hours ahead EST',
         'Remote Community Health Services', 'Sustainable Use of Fishery Resources'], axis=1)

In [5]:
df_sample = df_short.drop(['Gender', 'Teammate 1 (Repsondent #)', 'Teammate 2 (Repsondent #)'], axis=1)

### Client Preference Dropping

In [6]:
df_sample = df_sample.drop(['Client Preference'], axis=1)

In [7]:
df_sample1 = df_sample.drop(range(47, 55))

In [8]:
df_sample1.sort_values(by='Respondent #', ascending=True)

   Respondent #                                 Specialization
46            1                                    Engineering
0             2  Business/Commerce - Marketing and Advertising
20            3                                        Science
7             4                    Business/Commerce - General
2             5                                        Science
13            6                    Business/Commerce - General
32            7  Business/Commerce - Marketing and Advertising
40            8     Business/Commerce - Finance and Accounting
33            9                                    Engineering
27           10     Business/Commerce - Finance and Accounting
16           11     Business/Commerce - Finance and Accounting
30           12                                    Engineering
21           13                                   Liberal Arts
31           14                    Business/Commerce - General
39           15                                Health Sciences
24           16                                        Science
14           17     Business/Commerce - Finance and Accounting
43           18                                   Liberal Arts
34           19                                    Engineering
28           20                                   Liberal Arts
23           21  Business/Commerce - Marketing and Advertising
36           22                                        Science
18           23     Business/Commerce - Finance and Accounting
6            24                                        Science
41           25                                    Engineering
10           26                                Health Sciences
1            27                                    Mathematics
9            28                                    Engineering
4            29                    Business/Commerce - General
45           30                                   Liberal Arts
8            31                    Business/Commerce - General
3            32                                        Science
19           33                    Business/Commerce - General
15           34     Business/Commerce - Finance and Accounting
22           35                                        Science
38           36                                     Technology
35           37     Business/Commerce - Finance and Accounting
25           38  Business/Commerce - Marketing and Advertising
17           39     Business/Commerce - Finance and Accounting
29           40  Business/Commerce - Marketing and Advertising
5            41                                Health Sciences
44           42  Business/Commerce - Marketing and Advertising
11           43  Business/Commerce - Marketing and Advertising
26           44     Business/Commerce - Finance and Accounting
37           45                                        Science
42           46  Business/Commerce - Marketing and Advertising
12           47                                        Science

### Final Sample

In [9]:
df_sample1['Specialization'] = df_sample1['Specialization'].map({"Liberal Arts": 0,
                                                                "Health Sciences": 1,
                                                                "Science": 2,
                                                                "Technology": 3,
                                                                "Engineering": 4,
                                                                "Mathematics": 5,
                                                                "Business/Commerce - Marketing and Advertising": 6,
                                                                "Business/Commerce - Finance and Accounting": 7,
                                                                "Business/Commerce - General": 8})
df_sample1

   Respondent #  Specialization
0             2               6
1            27               5
2             5               2
3            32               2
4            29               8
5            41               1
6            24               2
7             4               8
8            31               8
9            28               4
10           26               1
11           43               6
12           47               2
13            6               8
14           17               7
15           34               7
16           11               7
17           39               7
18           23               7
19           33               8
20            3               2
21           13               0
22           35               2
23           21               6
24           16               2
25           38               6
26           44               7
27           10               7
28           20               0
29           40               6
30           12               4
31           14               8
32            7               6
33            9               4
34           19               4
35           37               7
36           22               2
37           45               2
38           36               3
39           15               1
40            8               7
41           25               4
42           46               6
43           18               0
44           42               6
45           30               0
46            1               4

# Interesting Part

# Calculation of Simpson's Diversity Index

In [10]:
species = df_sample1.groupby('Specialization').count()
species['n-1'] = species['Respondent #'] - 1
species['n(n-1)'] = species['Respondent #']*species['n-1']
species

                Respondent #  n-1  n(n-1)
Specialization
0                          4    3      12
1                          3    2       6
2                          9    8      72
3                          1    0       0
4                          6    5      30
5                          1    0       0
6                          8    7      56
7                          9    8      72
8                          6    5      30

In [11]:
nips = species['Respondent #'].sum()
tni = species['n(n-1)'].sum()
print (nips, tni)

47 278

In [12]:
SDI = 1- (tni/(nips*(nips-1)))
SDI

0.8714153561517114

# Randomize list

In [13]:
def randomize(population):
    shuffled_df = df_sample1.sample(frac=1).reset_index(drop=True)
    return shuffled_df

In [14]:
shuffled_df = randomize(df_sample1)

In [15]:
shuffled_df

   Respondent #  Specialization
0            46               6
1             1               4
2            30               0
3            22               2
4             3               2
5             4               8
6            26               1
7            10               7
8            25               4
9            21               6
10           23               7
11           14               8
12           28               4
13           12               4
14           19               4
15           27               5
16            5               2
17           47               2
18           35               2
19           29               8
20           13               0
21           42               6
22           43               6
23           32               2
24           18               0
25           34               7
26           39               7
27           38               6
28           15               1
29           44               7
30            7               6
31           40               6
32           31               8
33           41               1
34           37               7
35           20               0
36           16               2
37            9               4
38           36               3
39           17               7
40           45               2
41           33               8
42           11               7
43            6               8
44            2               6
45            8               7
46           24               2

# Group Creation

In [16]:
def herd_formation(population):
    for i in range(0,len(population.index),6):
        x = int(i/6)
        exec('herd{} = pd.DataFrame()'.format(x))
        globals()['herd{}'.format(x)] = population.iloc[i:i+6:, :]

## Diversity Index of Each Group

In [17]:
# A group can be a herd or the whole population
def calculate_SDI(group):
    species = group.groupby('Specialization').count()
    species['n-1'] = species['Respondent #'] - 1
    species['n(n-1)'] = species['Respondent #']*species['n-1']
    nips = species['Respondent #'].sum()
    tni = species['n(n-1)'].sum()
    #print(nips, tni)
    SDI = 1- (tni/(nips*(nips-1)))
    return SDI

In [18]:
calculate_SDI(df_sample1)

0.8714153561517114

## Mutation algorithm

The algorithm below takes a population dataframe a swap rows randomly and then form the herds

In [19]:
def mutate(population):
#    new_population = population
    first_random = random.randint(0, 46)
    second_random = random.randint(0, 46)
    individual_a, individual_b = population.iloc[first_random].copy(), population.iloc[second_random].copy()
    population.iloc[first_random], population.iloc[second_random] = individual_b, individual_a
    return population

### Example of mutation and calculation of SDI of new population

In [20]:
new_population = mutate(df_sample1)

In [21]:
herd_formation(new_population)

In [22]:
y = []
for i in range(0,int(len(df_sample1.index)/6)):
    x = calculate_SDI(globals()['herd{}'.format(i)])
    y.append(x)
    print(x)
mean(y)

0.9333333333333333
0.9333333333333333
0.6
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333

0.8571428571428572

## Evaluation algorithm

In [23]:
# In this case the average SDI and the standard deviation will be the values to evaluate the fitness of the population
def average_SDI(population):
    herd_formation(population)
    y = []
    for i in range(0,int(len(df_sample1.index)/6)):
        x = calculate_SDI(globals()['herd{}'.format(i)])
        y.append(x)
        print(x)
    a_SDI = mean(y)
    std_SDI = stdev(y)
    return (a_SDI, std_SDI)

In [24]:
average_SDI(new_population)

0.9333333333333333
0.9333333333333333
0.6
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333

(0.8571428571428572, 0.12429696476477393)

### This part doesn't matter at the moment

In [25]:
# In this case the parameter is the average SDI
def evaluate(population):
    a_SDI, std_SDI = average_SDI(population)
    diff = 0

# Hill Climbing algorithm

In [26]:
# Best is a scalar that represents the weighed average of the parameters to be considered
# Up to this point we are just considering diversity
best_order = df_sample1
best_score, std_best_score = average_SDI(best_order)

0.9333333333333333
0.9333333333333333
0.6
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333

In [27]:
while True:
    print('Best score so far', best_score, std_best_score)

    # if statement needs to be changed to be more accurate
    if (0.9 <= best_score <= 1) & (std_best_score <= 0.05):
        break

    new_order = best_order
    mutate(new_order)
    
    score, std_score = average_SDI(new_order)
    if not (0.9 <= best_score <= 1) & (std_best_score <= 0.05):
#    if std_best_score <= 0.035:
        best_order = new_order
        best_score = score
        std_best_score = std_score
print('best score:', best_score, std_best_score)

Best score so far 0.8571428571428572 0.12429696476477393
0.9333333333333333
0.9333333333333333
0.6
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8571428571428572 0.12429696476477393
0.9333333333333333
0.9333333333333333
0.6
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8571428571428572 0.12429696476477393
0.9333333333333333
0.9333333333333333
0.8
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8857142857142858 0.06341264874742278
0.9333333333333333
0.9333333333333333
0.8
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8857142857142858 0.06341264874742278
0.9333333333333333
0.9333333333333333
0.8
1.0
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8952380952380953 0.07559289460184543
0.8666666666666667
0.9333333333333333
0.8
1.0
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8857142857142858 0.07417981870189155
0.8666666666666667
0.9333333333333333
0.8
1.0
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8857142857142858 0.07417981870189155
0.8666666666666667
0.9333333333333333
0.8
1.0
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8857142857142858 0.07417981870189155
0.8666666666666667
0.9333333333333333
0.8
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8761904761904762 0.05998236072282914
0.8666666666666667
0.9333333333333333
0.8
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
Best score so far 0.8761904761904762 0.05998236072282914
0.8666666666666667
0.9333333333333333
0.8
0.9333333333333333
0.8666666666666667
0.9333333333333333
0.9333333333333333
Best score so far 0.8952380952380953 0.0524530528312962
0.8666666666666667
0.9333333333333333
0.8
0.9333333333333333
0.8666666666666667
0.9333333333333333
0.9333333333333333
Best score so far 0.8952380952380953 0.0524530528312962
0.8
0.9333333333333333
0.8
0.8666666666666667
0.8666666666666667
0.9333333333333333
0.9333333333333333
Best score so far 0.8761904761904762 0.05998236072282914
0.8
0.8666666666666667
0.8
0.8666666666666667
0.8666666666666667
0.8666666666666667
0.9333333333333333
Best score so far 0.8571428571428572 0.0460043706228236
0.8
0.8666666666666667
0.8
0.8666666666666667
0.8666666666666667
0.8666666666666667
0.8666666666666667
Best score so far 0.8476190476190476 0.032530002431617765
0.9333333333333333
0.8666666666666667
0.8
0.8666666666666667
0.8666666666666667
0.9333333333333333
0.8666666666666667
Best score so far 0.8761904761904762 0.0460043706228236
0.9333333333333333
0.8666666666666667
0.8
0.8666666666666667
0.8666666666666667
0.8666666666666667
0.8666666666666667
Best score so far 0.8666666666666667 0.03849001794597504
1.0
0.8666666666666667
0.8
0.8666666666666667
0.7333333333333334
0.8666666666666667
0.8666666666666667
Best score so far 0.8571428571428572 0.0809990528391941
0.9333333333333333
0.8666666666666667
0.8
0.8666666666666667
0.8666666666666667
0.8666666666666667
0.8666666666666667
Best score so far 0.8666666666666667 0.03849001794597504
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
0.8666666666666667
0.8666666666666667
0.8666666666666667
Best score so far 0.8761904761904762 0.0460043706228236
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
0.8666666666666667
0.8666666666666667
0.8666666666666667
Best score so far 0.8761904761904762 0.0460043706228236
0.9333333333333333
0.9333333333333333
0.8
0.9333333333333333
0.9333333333333333
0.8666666666666667
0.8666666666666667
Best score so far 0.8952380952380953 0.0524530528312962
0.9333333333333333
0.8666666666666667
0.8
0.9333333333333333
0.9333333333333333
0.8
0.8666666666666667
Best score so far 0.8761904761904762 0.05998236072282914
0.9333333333333333
0.9333333333333333
0.8
0.9333333333333333
0.9333333333333333
0.8666666666666667
0.8666666666666667
Best score so far 0.8952380952380953 0.0524530528312962
0.9333333333333333
0.9333333333333333
0.9333333333333333
0.9333333333333333
0.8666666666666667
0.8666666666666667
0.8666666666666667
Best score so far 0.9047619047619048 0.03563483225498991
best score: 0.9047619047619048 0.03563483225498991

In [29]:
herd4

   Respondent #  Specialization
24           16               2
25            9               4
26           10               7
27           17               7
28           35               2
29            4               8